### ISSUE TITLE
ghpages deploy tool

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/ideas#6]
gh-pages branch is often kinda annoying to deal with. e.g. forgetting to merge with master, accidentally committing to gh-pages instead of master, etc. 

one solution is to mirror master to gh-pages but then you end up committing bundle/release assets which is no good. 

another is a shell alias like so:

```
git checkout gh-pages \
  && git merge master \
  && npm run build \
  && git add . \
  && git commit -m 'build' \
  && git push origin gh-pages \
  && git checkout master 
```

but it does not handle cases where there is a merge conflict (pretty rare). maybe a tool like [ghrepo](https://github.com/mattdesl/ghrepo) could ease the work involved here.

**Comment by stoeffel** [comment]
[this](https://github.com/npm-scripts/scripts#gh-pages) often works out nicely (just pushing a dist or docs folder to the gh-pages branch)

**Comment by ungoldman** [comment]
@meandavejustice wrote a module to automate this process a bit:

https://www.npmjs.com/package/gh-pages-deploy
https://github.com/meandavejustice/gh-pages-deploy

**Comment by mattdesl** [comment]
This now handles my most common case:
https://github.com/mattdesl/ghpages
