### ISSUE TITLE
browserify plugin/transform for dynamic requires

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/ideas#8]
when the plugin finds a require statement that cannot be resolved, it triggers an `npm install [the-module] --save`.

i.e. no need to ever `npm install` manually again, just type and go.

**Comment by zeke** [comment]
:+1:

**Comment by mattdesl** [comment]
heh @zeke shortly after I posted this, I found hugh's transform:
https://github.com/hughsk/installify

With some tweaks it can accept `--save` option:
https://github.com/mattdesl/installify/tree/coolness
